
# rustfmt.toml for libpath.Rust
#
# configured for cargo-fmt 1.7.0-nightly

# array_width=60 # deprecated
# attr_fn_like_width=70 # deprecated
binop_separator="Front"
blank_lines_lower_bound=0
blank_lines_upper_bound=3
brace_style="SameLineWhere"
# chain_width=60 # deprecated
color="Auto"
combine_control_expr=false
comment_width=100
condense_wildcard_suffixes=false
control_brace_style="AlwaysSameLine"
disable_all_formatting=false
edition="2018"
empty_item_single_line=false
enum_discrim_align_threshold=0
error_on_line_overflow=false
error_on_unformatted=false
# fn_args_layout="Vertical"
# fn_call_width=60 # deprecated
fn_params_layout="Vertical"
fn_single_line=false
force_explicit_abi=true
force_multiline_blocks=true
# force_code_in_doc_comments=true
format_macro_bodies=true
format_macro_matchers=true
format_strings=false
group_imports="Preserve"
hard_tabs=false
hide_parse_errors=false
ignore=[

]
imports_granularity="Crate"
imports_indent="Block"
imports_layout="Vertical"
indent_style="Block"
inline_attribute_width=0
# license_template_path=""
match_arm_blocks=true
match_arm_leading_pipes="Preserve"
match_block_trailing_comma=true
max_width=120
merge_derives=false
# merge_imports= # deprecated
newline_style="Auto"
normalize_comments=false
normalize_doc_attributes=true
overflow_delimited_expr=false
remove_nested_parens=true
reorder_impl_items=true
reorder_imports=true
reorder_modules=true
# report_fixme="Always"
# report_todo="Never"
# required_version="????"
# single_line_if_else_max_width=0 # deprecated
skip_children=false
space_after_colon=true
space_before_colon=true
spaces_around_ranges=false
struct_field_align_threshold=20
struct_lit_single_line=false
# struct_lit_width=0 # deprecated
# struct_variant_width=0 # deprecated
tab_spaces=4 # Q: do we want to move to 2??
trailing_comma="Vertical"
trailing_semicolon=true
type_punctuation_density="Wide"
# unstable_features=false
use_field_init_shorthand=true
use_small_heuristics="Default"
use_try_shorthand=true
# version=
where_single_line=false
wrap_comments=false

